// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkJqpPCEWu7k28c0wL7XpLdutCcL_So6U',
    appId: '1:586338917135:web:a3215564075b4e538c3c7a',
    messagingSenderId: '586338917135',
    projectId: 'chatapp-41f15',
    authDomain: 'chatapp-41f15.firebaseapp.com',
    storageBucket: 'chatapp-41f15.firebasestorage.app',
    measurementId: 'G-F2TRCLL273',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ufLSN-cdizyfV1HhxYj9tsYTnn5zKa4',
    appId: '1:586338917135:android:96468c9229a437748c3c7a',
    messagingSenderId: '586338917135',
    projectId: 'chatapp-41f15',
    storageBucket: 'chatapp-41f15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9OPfYOVmym9MHDCxXXU_efoXglhEOccU',
    appId: '1:586338917135:ios:bdc6cea04f5802408c3c7a',
    messagingSenderId: '586338917135',
    projectId: 'chatapp-41f15',
    storageBucket: 'chatapp-41f15.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9OPfYOVmym9MHDCxXXU_efoXglhEOccU',
    appId: '1:586338917135:ios:bdc6cea04f5802408c3c7a',
    messagingSenderId: '586338917135',
    projectId: 'chatapp-41f15',
    storageBucket: 'chatapp-41f15.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkJqpPCEWu7k28c0wL7XpLdutCcL_So6U',
    appId: '1:586338917135:web:2d75e91637d97de48c3c7a',
    messagingSenderId: '586338917135',
    projectId: 'chatapp-41f15',
    authDomain: 'chatapp-41f15.firebaseapp.com',
    storageBucket: 'chatapp-41f15.firebasestorage.app',
    measurementId: 'G-0FTCDBRNWF',
  );
}
